# Generated by Django 5.2.15 on 2026-06-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SLACK', 'Slack'), ('TEAMS', 'Microsoft Teams')], default='SLACK', max_length=10)),
                ('webhook_url', models.URLField(blank=True, max_length=1000, verbose_name='Webhook URL')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='Notify on failure')),
                ('notify_on_timeout', models.BooleanField(default=True, verbose_name='Notify on timeout')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Script Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('script_path', models.CharField(max_length=500, verbose_name='Script File Path')),
                ('working_directory', models.CharField(blank=True, max_length=500, verbose_name='Working Directory (CWD)')),
                ('cron_expression', models.CharField(blank=True, help_text='Standard cron syntax, e.g.: 0 2 * * *  (if left empty, it is not scheduled automatically)', max_length=100, verbose_name='Cron Schedule')),
                ('timeout_seconds', models.PositiveIntegerField(default=3600, verbose_name='Timeout (s)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['name'],
            },
        ),
    ]
