# Generated by Django 5.2.15 on 2026-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, verbose_name='Environment variables'),
        ),
        migrations.AddField(
            model_name='job',
            name='grace_period_seconds',
            field=models.PositiveIntegerField(default=300, verbose_name='Grace period (s)'),
        ),
        migrations.AddField(
            model_name='job',
            name='last_missed_alert_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='run_parameters',
            field=models.JSONField(blank=True, default=list, verbose_name='Run parameters'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='Send email alerts'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated email addresses.', max_length=1000, verbose_name='Email recipients'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='min_consecutive_failures',
            field=models.PositiveIntegerField(default=1, verbose_name='Alert after N consecutive failures'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_on_missed',
            field=models.BooleanField(default=True, verbose_name='Notify on missed run'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_on_recovery',
            field=models.BooleanField(default=True, verbose_name='Notify on recovery'),
        ),
    ]
